version: '2'
services:
  php:
    # image: yiisoftware/yii2-php:7.4-apache
    container_name: sabutta_jm_api2-php
    image: yiisoftware/yii2-php:8.0-apache
    ports:
      - '8023:80'
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    networks:
      - sabutta_jm2_prod
  
  wabot:
    build:
      context: ./wa-bot
      dockerfile: Dockerfile
    image: nodejs
    container_name: sabutta_jm_api2-node
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./wa-bot:/home/node/app
      - ./wa-bot/node_modules:/home/node/app/node_modules
      # - ./wa-bot/node_modules:/home/node/app/node_modules
    networks:
      - sabutta_jm2_prod

networks: 
  sabutta_jm2_prod:

volumes:
  node_modules: 

