version: '2'
services:
  php:
    # image: yiisoftware/yii2-php:7.4-apache
    image: yiisoftware/yii2-php:8.1-apache
    ports:
      - '6001:80'
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    networks:
      - sabutta

  db:
    image: mysql:5.7
    networks:
      - sabutta
    environment:
      MYSQL_DATABASE: pupr
      # So you don't have to use root, but you can if you like
      MYSQL_USER: admin
      # You can use whatever password you like
      MYSQL_PASSWORD: admin
      # Password for root access
      MYSQL_ROOT_PASSWORD: Fasyankes!@#
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '4306:3306'
    expose:
      # Opens port 3306 on the container
      - '4306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  
  api-service:
    container_name: sabutta_api-service
    image: sabutta_api-service
    build:
      context: ./java
    depends_on:
      - db
    ports:
      - "8090:8090"
    networks:
      - sabutta
  
  proxy-service:
    container_name: sabutta_proxy-service
    image: sabutta_proxy-service
    build:
      context: ./java/proxy
    depends_on:
      - db
    ports:
      - "8091:8091"
    networks:
      - sabutta
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - 6002:80
    networks:
      - sabutta
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: Fasyankes!@#
      PMA_HOST: db


networks: 
  sabutta:

volumes:
  my-db: